openapi: '3.0.2'
info:
  title: Entcore Admin
  description: entcore API for administrative tasks
  version: '1.0'
servers:
- url: http://localhost:8090
  description: Optional dev mode server
paths:
  # PlatformInfoController
  /admin/api/platform/module/sms:
    get:
      # Droit requis : admin
      responses:
        '200':
          description: OK - returns the current sms module activation state.
          content:
            application/json:
              schema:
                type: object
                properties:
                  activated:
                    type: boolean
                example:
                  activated: true
  # PlatformInfoController
  /admin/api/platform/config:
    get:
      # Droit requis : admin
      responses:
        '200':
          description: OK - returns the current platform config.
          content:
            application/json: {}
